nelmio_cors:
    defaults:
        allow_origin: ['*']        # Autorise toutes les origines (*)
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        allow_headers: ['Content-Type', 'Authorization']
        expose_headers: ['Link']
        max_age: 3600
        hosts: []
        origin_regex: false
    paths:
        '^/api/':                   # Configuration pour les chemins commençant par /api/
            allow_origin: ['*']
            allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
            allow_headers: ['Content-Type', 'Authorization']
            max_age: 3600
        '^/':                       # Configuration générale pour toutes les routes
            allow_origin: ['*']
            allow_methods: ['GET', 'POST', 'OPTIONS']
