services:
  # Service pour l'application Symfony
  symfony:
    build: .
    container_name: symfony_app
    ports:
      - "5000:5000"  # Mappe le port 5000 du conteneur au port 5000 de l'hôte
    volumes:
      - ./code-source:/var/www/html  # Monte le répertoire local 'code-source' dans le conteneur
    environment:
      - DATABASE_URL=pgsql:host=db;port=5432;dbname=accessapi  # Connexion à PostgreSQL via le service db
    depends_on:
      - db  # L'application dépend du service 'db'

  # Service pour la base de données PostgreSQL
  db:
    image: postgres:15.3
    container_name: symfony_db
    environment:
      POSTGRES_DB: accessapi  # Base de données à créer
      POSTGRES_USER: api  # Utilisateur de la base
      POSTGRES_PASSWORD: api  # Mot de passe de l'utilisateur
    ports:
      - "5432:5432"  # Mappe le port PostgreSQL du conteneur au port 5432 de l'hôte
    volumes:
      - db_data:/var/lib/postgresql/data  # Volume pour persister les données de la base

volumes:
  db_data:  # Définit un volume nommé pour stocker les données PostgreSQL
